export const myShops = [
	{
		id: "1",
		name: "Grab & Go Foods East Legon",
		price: "3.00",
		date: "13 Oct, 2021 8:52 PM",
		status: "Delivered",
		// image: require("../assets/images/food/fried-rice.jpg"),
	},
	{
		id: "2",
		name: "Aseda Restaurant",
		price: "4.00",
		date: "13 Oct, 2021 8:52 PM",
		status: "Delivered",
		// image: require("../assets/images/food/pizza.jpg"),
	},
	{
		id: "3",
		name: "KFC East Legon",
		price: "2.00",
		date: "13 Oct, 2021 8:52 PM",
		status: "Delivered",
		// image: require("../assets/images/food/chicken.jpg"),
	},
	{
		id: "4",
		name: "Rocomamas",
		price: "5.00",
		date: "13 Oct, 2021 8:52 PM",
		status: "Delivered",
		// image: require("../assets/images/food/rocomamas.jpg"),
	},

	{
		id: "5",
		name: "Grab & Go Foods East Legon",
		price: "3.00",
		date: "13 Oct, 2021 8:52 PM",
		status: "Delivered",
		// image: require("../assets/images/food/fried-rice.jpg"),
	},
	{
		id: "6",
		name: "Aseda Restaurant",
		price: "4.00",
		date: "13 Oct, 2021 8:52 PM",
		status: "Delivered",
		// image: require("../assets/images/food/pizza.jpg"),
	},
	{
		id: "7",
		name: "KFC East Legon",
		price: "2.00",
		date: "13 Oct, 2021 8:52 PM",
		status: "Delivered",
		// image: require("../assets/images/food/kfc.png"),
	},
	{
		id: "8",
		name: "Rocomamas",
		price: "5.00",
		date: "13 Oct, 2021 8:52 PM",
		status: "Delivered",
		// image: require("../assets/images/food/burger.jpg"),
	},
];